Added missing variable check and testing for failure

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -11,6 +11,11 @@ if [ -z "${API_KEY_VALUE}" ]; then
   exit 1
 fi
 
+if [ -z "${FILES_PATTERN}" ]; then
+  echo "Missing configuration for files to search for"
+  exit 1
+fi
+
 matching_files=()
 while IFS=$'' read -r matching_file ; do
   matching_files+=("$matching_file")
